### ISSUE TITLE
Widget fails when refreshing context object in 8.12.5

### ISSUE THREAD

**Issue by JeroenAppel** [Itvisors/mendix-AutocompleteMultiselect#1] opened 2021-01-26 10:25 UTC
First of all; thanks for your attribution to the Mendix Marketplace! The look and feel of this widget are definitely an improvement over the existing autocomplete.

Unfortunately, I run into an issue when refreshing the context object. First, I was using an on change action in which I set an association between the selected option and the context object. A refresh of this object will cause the widget to fail and disappear. Later on, I tried to move this action to the commit action. Unfortunately, there is another action on the page that requires an object refresh. This is causing the same error.

The following stack trace is shown in the console.

`_this2.optionsSelected.find is not a function TypeError: _this2.optionsSelected.find is not a function
    at http://localhost:1111/widgets/itvisors/autocompletemultiselect/AutocompleteMultiselect.js?637472564962831214:31181:42
    at Array.map (<anonymous>)
    at AutocompleteMultiselect.componentDidUpdate (http://localhost:1111/widgets/itvisors/autocompletemultiselect/AutocompleteMultiselect.js?637472564962831214:31157:61)
    at Es (http://localhost:1111/mxclientsystem/mxui/mxui.js?637472564962831214:62:94638)
    at t.unstable_runWithPriority (http://localhost:1111/mxclientsystem/mxui/mxui.js?637472564962831214:80:3881)
    at hi (http://localhost:1111/mxclientsystem/mxui/mxui.js?637472564962831214:62:41484)
    at js (http://localhost:1111/mxclientsystem/mxui/mxui.js?637472564962831214:62:90549)
    at ps (http://localhost:1111/mxclientsystem/mxui/mxui.js?637472564962831214:62:79288)
    at http://localhost:1111/mxclientsystem/mxui/mxui.js?637472564962831214:62:41756
    at t.unstable_runWithPriority (http://localhost:1111/mxclientsystem/mxui/mxui.js?637472564962831214:80:3881)`

**Comment by jeuhen** [comment] 2021-01-29 07:21
Hi Jeroen,

Thanks for your feedback! I think I am able to reproduce your bug, is it correct that you are using the single select option?
Also please note that the minimal mendix version for this widget is 8.15, since there are some fixes done wrt the data source.

**Comment by JeroenAppel** [comment] 2021-02-02 07:40
Hi Johan,

Thanks for coming back to me on this! It is correct that I was using the single select option. You are correct indeed that I tried to push the boundaries a little further regarding the Mendix version. Currently, we’ve upgraded to the new LTS version 8.18.1. If there is any room for me to verify this behavior in the higher version, I will let you know.

Kind regards,
Jeroen

**Comment by jeuhen** [comment] 2021-02-02 09:03
Hi Jeroen,

No problem. I was able to reproduce the bug and deployed a new version yesterday. Please let me know whether this will fix your problem. I will close this issue for now.

Kind regards,

Johan

**Closed as completed by jeuhen** 2021-02-02 09:03 UTC
